/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.faistdev.fwlstsim.ui.calltaker;

/**
 *
 * @author Ben
 */
public class CallTakerUi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CallTakerUi.class.getName());

    /**
     * Creates new form CallTakerUi
     */
    public CallTakerUi() {
        initComponents();
    }

    private void refreshIncomingCalls() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        incomingCallsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        callPromptsPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        connectedCallPanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        btnPickUpCall = new javax.swing.JButton();
        talkingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        leftPanel.setLayout(new java.awt.GridLayout(2, 0));

        incomingCallsPanel.setLayout(new javax.swing.BoxLayout(incomingCallsPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setText("+43 6649601122");
        jPanel1.add(jLabel1);

        incomingCallsPanel.add(jPanel1);

        leftPanel.add(incomingCallsPanel);

        javax.swing.GroupLayout callPromptsPanelLayout = new javax.swing.GroupLayout(callPromptsPanel);
        callPromptsPanel.setLayout(callPromptsPanelLayout);
        callPromptsPanelLayout.setHorizontalGroup(
            callPromptsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        callPromptsPanelLayout.setVerticalGroup(
            callPromptsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        leftPanel.add(callPromptsPanel);

        getContentPane().add(leftPanel);

        rightPanel.setLayout(new java.awt.GridLayout(1, 0));

        connectedCallPanel.setLayout(new javax.swing.BoxLayout(connectedCallPanel, javax.swing.BoxLayout.Y_AXIS));

        actionPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        actionPanel.setLayout(new java.awt.GridLayout());

        btnPickUpCall.setText("Anruf annehmen");
        btnPickUpCall.setMaximumSize(new java.awt.Dimension(120, 50));
        btnPickUpCall.setPreferredSize(new java.awt.Dimension(120, 50));
        actionPanel.add(btnPickUpCall);

        connectedCallPanel.add(actionPanel);

        javax.swing.GroupLayout talkingPanelLayout = new javax.swing.GroupLayout(talkingPanel);
        talkingPanel.setLayout(talkingPanelLayout);
        talkingPanelLayout.setHorizontalGroup(
            talkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        talkingPanelLayout.setVerticalGroup(
            talkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        connectedCallPanel.add(talkingPanel);

        rightPanel.add(connectedCallPanel);

        getContentPane().add(rightPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CallTakerUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnPickUpCall;
    private javax.swing.JPanel callPromptsPanel;
    private javax.swing.JPanel connectedCallPanel;
    private javax.swing.JPanel incomingCallsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel talkingPanel;
    // End of variables declaration//GEN-END:variables
}
