/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.faistdev.fwlstsim.ui;

/**
 *
 * @author Ben
 */
public class DispatchUi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DispatchUi.class.getName());

    /**
     * Creates new form DispatchUi
     */
    public DispatchUi() {
        initComponents();
    }

    private void onSelectVehiclesBtnClick() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectVehiclesDialog = new javax.swing.JDialog();
        toolbarPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        saveVehiclesButton = new javax.swing.JButton();
        selectVehiclesScrollPanel = new javax.swing.JScrollPane();
        innerSelectVehiclesScrollPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        toolPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        selectVehiclesButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(500, 0));
        dispatchButton = new javax.swing.JButton();
        lowerPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        callerNumberPanel = new javax.swing.JPanel();
        callerNumberLabel = new javax.swing.JLabel();
        callerNumberField = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        adressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        keywordPanel = new javax.swing.JPanel();
        keywordLabel = new javax.swing.JLabel();
        keywordComboBox = new javax.swing.JComboBox<>();
        infoTextPanel = new javax.swing.JPanel();
        infoTextLabel = new javax.swing.JLabel();
        infoTextField = new javax.swing.JTextField();
        vehiclesPanel = new javax.swing.JPanel();
        assignedVehiclesScrollPanel = new javax.swing.JScrollPane();
        innerAssignedVehiclesScrollPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();

        selectVehiclesDialog.getContentPane().setLayout(new javax.swing.BoxLayout(selectVehiclesDialog.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        toolbarPanel.setBackground(new java.awt.Color(255, 255, 255));
        toolbarPanel.setMaximumSize(new java.awt.Dimension(32767, 33));
        toolbarPanel.setMinimumSize(new java.awt.Dimension(0, 23));
        toolbarPanel.setPreferredSize(new java.awt.Dimension(374, 33));
        toolbarPanel.setLayout(new javax.swing.BoxLayout(toolbarPanel, javax.swing.BoxLayout.X_AXIS));
        toolbarPanel.add(filler2);

        saveVehiclesButton.setText("Speichern");
        toolbarPanel.add(saveVehiclesButton);

        selectVehiclesDialog.getContentPane().add(toolbarPanel);

        selectVehiclesScrollPanel.setBackground(new java.awt.Color(255, 255, 255));

        innerSelectVehiclesScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        innerSelectVehiclesScrollPanel.setLayout(new javax.swing.BoxLayout(innerSelectVehiclesScrollPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("3");
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TLF 1000 Blumegg Teipl");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel1.add(jLabel1);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jCheckBox1);

        innerSelectVehiclesScrollPanel.add(jPanel1);

        selectVehiclesScrollPanel.setViewportView(innerSelectVehiclesScrollPanel);

        selectVehiclesDialog.getContentPane().add(selectVehiclesScrollPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        toolPanel.setMaximumSize(new java.awt.Dimension(10000, 33));
        toolPanel.setPreferredSize(new java.awt.Dimension(400, 33));
        toolPanel.setLayout(new javax.swing.BoxLayout(toolPanel, javax.swing.BoxLayout.X_AXIS));
        toolPanel.add(filler1);

        selectVehiclesButton.setText("Fahrzeug wählen");
        selectVehiclesButton.addActionListener(this::selectVehiclesButtonActionPerformed);
        toolPanel.add(selectVehiclesButton);
        toolPanel.add(filler3);

        dispatchButton.setText("Alarmieren");
        dispatchButton.setEnabled(false);
        toolPanel.add(dispatchButton);

        getContentPane().add(toolPanel);

        lowerPanel.setLayout(new java.awt.GridLayout(1, 2));

        dataPanel.setLayout(new javax.swing.BoxLayout(dataPanel, javax.swing.BoxLayout.Y_AXIS));

        callerNumberPanel.setMaximumSize(new java.awt.Dimension(10000, 50));
        callerNumberPanel.setLayout(new javax.swing.BoxLayout(callerNumberPanel, javax.swing.BoxLayout.Y_AXIS));

        callerNumberLabel.setLabelFor(addressField);
        callerNumberLabel.setText("Telefonnummer");
        callerNumberLabel.setMaximumSize(new java.awt.Dimension(1000, 16));
        callerNumberPanel.add(callerNumberLabel);

        callerNumberField.setAlignmentX(0.0F);
        callerNumberField.setEnabled(false);
        callerNumberPanel.add(callerNumberField);

        dataPanel.add(callerNumberPanel);

        addressPanel.setAlignmentX(0.0F);
        addressPanel.setMaximumSize(new java.awt.Dimension(10000, 50));
        addressPanel.setLayout(new javax.swing.BoxLayout(addressPanel, javax.swing.BoxLayout.Y_AXIS));

        adressLabel.setLabelFor(addressField);
        adressLabel.setText("Adresse");
        adressLabel.setMaximumSize(new java.awt.Dimension(1000, 16));
        addressPanel.add(adressLabel);

        addressField.setAlignmentX(0.0F);
        addressField.setEnabled(false);
        addressPanel.add(addressField);

        dataPanel.add(addressPanel);

        keywordPanel.setMaximumSize(new java.awt.Dimension(10000, 50));
        keywordPanel.setLayout(new javax.swing.BoxLayout(keywordPanel, javax.swing.BoxLayout.Y_AXIS));

        keywordLabel.setLabelFor(addressField);
        keywordLabel.setText("Einsatzstichwort");
        keywordLabel.setMaximumSize(new java.awt.Dimension(1000, 16));
        keywordPanel.add(keywordLabel);

        keywordComboBox.setAlignmentX(0.0F);
        keywordPanel.add(keywordComboBox);

        dataPanel.add(keywordPanel);

        infoTextPanel.setMaximumSize(new java.awt.Dimension(10000, 50));
        infoTextPanel.setLayout(new javax.swing.BoxLayout(infoTextPanel, javax.swing.BoxLayout.Y_AXIS));

        infoTextLabel.setLabelFor(addressField);
        infoTextLabel.setText("Info");
        infoTextLabel.setMaximumSize(new java.awt.Dimension(1000, 16));
        infoTextPanel.add(infoTextLabel);

        infoTextField.setAlignmentX(0.0F);
        infoTextPanel.add(infoTextField);

        dataPanel.add(infoTextPanel);

        lowerPanel.add(dataPanel);

        vehiclesPanel.setLayout(new javax.swing.BoxLayout(vehiclesPanel, javax.swing.BoxLayout.Y_AXIS));

        assignedVehiclesScrollPanel.setBackground(new java.awt.Color(255, 255, 255));

        innerAssignedVehiclesScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        innerAssignedVehiclesScrollPanel.setLayout(new javax.swing.BoxLayout(innerAssignedVehiclesScrollPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jTextField2.setBackground(new java.awt.Color(255, 255, 153));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("3");
        jTextField2.setEnabled(false);
        jTextField2.setMaximumSize(new java.awt.Dimension(50, 2147483647));
        jPanel2.add(jTextField2);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TLF 1000 Blumegg Teipl");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 18));
        jLabel2.setMinimumSize(new java.awt.Dimension(250, 18));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 18));
        jPanel2.add(jLabel2);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jCheckBox2);

        innerAssignedVehiclesScrollPanel.add(jPanel2);

        assignedVehiclesScrollPanel.setViewportView(innerAssignedVehiclesScrollPanel);

        vehiclesPanel.add(assignedVehiclesScrollPanel);

        lowerPanel.add(vehiclesPanel);

        getContentPane().add(lowerPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectVehiclesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectVehiclesButtonActionPerformed
        onSelectVehiclesBtnClick();
    }//GEN-LAST:event_selectVehiclesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DispatchUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JScrollPane assignedVehiclesScrollPanel;
    private javax.swing.JTextField callerNumberField;
    private javax.swing.JLabel callerNumberLabel;
    private javax.swing.JPanel callerNumberPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton dispatchButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JTextField infoTextField;
    private javax.swing.JLabel infoTextLabel;
    private javax.swing.JPanel infoTextPanel;
    private javax.swing.JPanel innerAssignedVehiclesScrollPanel;
    private javax.swing.JPanel innerSelectVehiclesScrollPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> keywordComboBox;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JPanel keywordPanel;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JButton saveVehiclesButton;
    private javax.swing.JButton selectVehiclesButton;
    private javax.swing.JDialog selectVehiclesDialog;
    private javax.swing.JScrollPane selectVehiclesScrollPanel;
    private javax.swing.JPanel toolPanel;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JPanel vehiclesPanel;
    // End of variables declaration//GEN-END:variables
}
