/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.faistdev.fwlstsim.ui;

import at.faistdev.fwlstsim.bl.game.GameProperties;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Ben
 */
public class GameUi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameUi.class.getName());

    private final LocalDateTime startTime;
    private final DateTimeFormatter formatter;

    /**
     * Creates new form GameUi
     */
    public GameUi() {
        startTime = LocalDateTime.now();
        formatter = DateTimeFormatter.ofPattern("HH:mm:ss", Locale.forLanguageTag("de-AT"));
        initComponents();
        setEnabledStateBasedOnGameSpeed();
    }

    public synchronized void setTime(long currentTick) {
        LocalDateTime currentGameTime = startTime.plusSeconds(currentTick);
        timeLabel.setText(currentGameTime.format(formatter));
    }

    private void setEnabledStateBasedOnGameSpeed() {
        int gameSpeed = GameProperties.SPEED;
        pauseBtn.setEnabled(true);
        x1Btn.setEnabled(true);
        x2Btn.setEnabled(true);
        x4Btn.setEnabled(true);
        x8Btn.setEnabled(true);

        switch (gameSpeed) {
            case 0:
                pauseBtn.setEnabled(false);
                break;
            case 1:
                x1Btn.setEnabled(false);
                break;
            case 2:
                x2Btn.setEnabled(false);
                break;
            case 4:
                x4Btn.setEnabled(false);
                break;
            case 8:
                x8Btn.setEnabled(false);
                break;
        }
    }

    private void setSpeed(int speed) {
        GameProperties.SPEED = speed;
        setEnabledStateBasedOnGameSpeed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pauseBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        x1Btn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        x2Btn = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        x4Btn = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        x8Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spielsteuerung");
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 16));
        jPanel3.setLayout(new java.awt.GridLayout());

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("00:00:00");
        jPanel3.add(timeLabel);

        jPanel1.add(jPanel3);

        jLabel1.setText("Geschwindigkeit");
        jPanel1.add(jLabel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        pauseBtn.setText("Pause");
        pauseBtn.addActionListener(this::pauseBtnActionPerformed);
        jPanel2.add(pauseBtn);
        jPanel2.add(filler1);

        x1Btn.setText("1x");
        x1Btn.addActionListener(this::x1BtnActionPerformed);
        jPanel2.add(x1Btn);
        jPanel2.add(filler2);

        x2Btn.setText("2x");
        x2Btn.addActionListener(this::x2BtnActionPerformed);
        jPanel2.add(x2Btn);
        jPanel2.add(filler3);

        x4Btn.setText("4x");
        x4Btn.addActionListener(this::x4BtnActionPerformed);
        jPanel2.add(x4Btn);
        jPanel2.add(filler4);

        x8Btn.setText("8x");
        x8Btn.addActionListener(this::x8BtnActionPerformed);
        jPanel2.add(x8Btn);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBtnActionPerformed
        setSpeed(0);
    }//GEN-LAST:event_pauseBtnActionPerformed

    private void x1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1BtnActionPerformed
        setSpeed(1);
    }//GEN-LAST:event_x1BtnActionPerformed

    private void x2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2BtnActionPerformed
        setSpeed(2);
    }//GEN-LAST:event_x2BtnActionPerformed

    private void x4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4BtnActionPerformed
        setSpeed(4);
    }//GEN-LAST:event_x4BtnActionPerformed

    private void x8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x8BtnActionPerformed
        setSpeed(8);
    }//GEN-LAST:event_x8BtnActionPerformed

    public static void create() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GameUi ui = new GameUi();
            ui.setVisible(true);

            UiRegistry.add(ui);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pauseBtn;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton x1Btn;
    private javax.swing.JButton x2Btn;
    private javax.swing.JButton x4Btn;
    private javax.swing.JButton x8Btn;
    // End of variables declaration//GEN-END:variables
}
