/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.faistdev.fwlstsim.ui;

import at.faistdev.fwlstsim.dataaccess.cache.OperationCache;
import at.faistdev.fwlstsim.dataaccess.entities.Operation;
import at.faistdev.fwlstsim.dataaccess.entities.OperationStatus;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ben
 */
public class OperationListUi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OperationListUi.class.getName());

    private final DefaultTableModel model;

    /**
     * Creates new form OperationListUi
     */
    public OperationListUi() {
        initComponents();

        model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                getColumns()
        );
        table.setModel(model);

        startRefreshThreads();
    }

    private void startRefreshThreads() {
        new Thread(() -> {
            while (true) {
                refresh();
                try {
                    Thread.sleep(5_000);
                } catch (InterruptedException ex) {
                    System.getLogger(OperationListUi.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        }, "OperationListUi-FillTable").start();
    }

    public synchronized void refresh() {
        fillTable();
    }

    private void fillTable() {
        model.setRowCount(0);
        Object[][] tableData = getTableData();
        for (int i = 0; i < tableData.length; i++) {
            Object[] row = tableData[i];
            model.addRow(row);
        }
    }

    private String[] getColumns() {
        return new String[]{"ID", "Stichwort", "Info", "Adresse", "Fortschritt"};
    }

    private Object[][] getTableData() {
        List<Operation> operations = OperationCache.getCache().getAll().stream()//
                .filter(operation -> operation.getStatus() == OperationStatus.CALL_ANSWERED)//
                .collect(Collectors.toList());

        Object[][] data = new Object[operations.size()][];
        int i = 0;
        for (Operation operation : operations) {
            String keyword = operation.getOperationKeyword() != null ? operation.getOperationKeyword().getName() : "";
            Object[] row = {operation.getId(), keyword, "", operation.getLocation().getText(), operation.getProgressInPercent() + " %"};

            data[i] = row;
            i++;
        }

        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Einsatzübersicht");
        getContentPane().setLayout(new java.awt.GridLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void create() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            OperationListUi ui = new OperationListUi();
            ui.setVisible(true);

            UiRegistry.add(ui);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
