/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.faistdev.fwlstsim.ui;

/**
 *
 * @author Ben
 */
public class RadioUi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RadioUi.class.getName());

    /**
     * Creates new form RadioUi
     */
    public RadioUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestScrollPanel = new javax.swing.JScrollPane();
        requestPanel = new javax.swing.JPanel();
        demoRadioRequest = new javax.swing.JPanel();
        demoRadioRequestLabel = new javax.swing.JLabel();
        demoRadioRequestFiller = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        demoRadioRequestVehicleLabel = new javax.swing.JLabel();
        messagesScrollPanel = new javax.swing.JScrollPane();
        messagesPanel = new javax.swing.JPanel();
        demoRightPanel = new javax.swing.JPanel();
        demoRightFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        demoRightLabel = new javax.swing.JLabel();
        demoLeftPanel = new javax.swing.JPanel();
        demoLeftLabel = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        callVehiclePanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        callVehicleField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        callButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        responsePanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        repsoneEndMessageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funk");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        requestScrollPanel.setAlignmentX(0.0F);
        requestScrollPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        requestScrollPanel.setMinimumSize(new java.awt.Dimension(16, 100));

        requestPanel.setLayout(new javax.swing.BoxLayout(requestPanel, javax.swing.BoxLayout.Y_AXIS));

        demoRadioRequest.setAlignmentX(0.0F);
        demoRadioRequest.setMinimumSize(new java.awt.Dimension(214, 23));
        demoRadioRequest.setPreferredSize(new java.awt.Dimension(214, 23));
        demoRadioRequest.setLayout(new javax.swing.BoxLayout(demoRadioRequest, javax.swing.BoxLayout.X_AXIS));

        demoRadioRequestLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        demoRadioRequestLabel.setText("Sprechwunsch:");
        demoRadioRequestLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        demoRadioRequestLabel.setMaximumSize(new java.awt.Dimension(100, 23));
        demoRadioRequest.add(demoRadioRequestLabel);
        demoRadioRequest.add(demoRadioRequestFiller);

        demoRadioRequestVehicleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        demoRadioRequestVehicleLabel.setText("TLF 1000 Blumegg Teipl");
        demoRadioRequestVehicleLabel.setMaximumSize(new java.awt.Dimension(400, 16));
        demoRadioRequest.add(demoRadioRequestVehicleLabel);

        requestPanel.add(demoRadioRequest);

        requestScrollPanel.setViewportView(requestPanel);

        getContentPane().add(requestScrollPanel);

        messagesScrollPanel.setAlignmentX(0.0F);
        messagesScrollPanel.setMaximumSize(new java.awt.Dimension(32767, 300));

        messagesPanel.setLayout(new javax.swing.BoxLayout(messagesPanel, javax.swing.BoxLayout.Y_AXIS));

        demoRightPanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        demoRightPanel.setLayout(new javax.swing.BoxLayout(demoRightPanel, javax.swing.BoxLayout.X_AXIS));
        demoRightPanel.add(demoRightFiller);

        demoRightLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        demoRightLabel.setText("TLF 1000 Blumegg Teipl von Florian Steiermark kommen");
        demoRightLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        demoRightLabel.setMaximumSize(new java.awt.Dimension(300, 60));
        demoRightPanel.add(demoRightLabel);

        messagesPanel.add(demoRightPanel);

        demoLeftPanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        demoLeftPanel.setLayout(new javax.swing.BoxLayout(demoLeftPanel, javax.swing.BoxLayout.X_AXIS));

        demoLeftLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        demoLeftLabel.setText("<html>Hier TLF 1000 Blumegg Teipl, PKW in Graben, keine weiteren Kräfte benötigt</html>");
        demoLeftLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        demoLeftLabel.setMaximumSize(new java.awt.Dimension(300, 60));
        demoLeftPanel.add(demoLeftLabel);

        messagesPanel.add(demoLeftPanel);

        messagesScrollPanel.setViewportView(messagesPanel);

        getContentPane().add(messagesScrollPanel);

        actionPanel.setMaximumSize(new java.awt.Dimension(32767, 66));
        actionPanel.setPreferredSize(new java.awt.Dimension(647, 66));
        actionPanel.setLayout(new javax.swing.BoxLayout(actionPanel, javax.swing.BoxLayout.Y_AXIS));

        callVehiclePanel.setAlignmentX(0.0F);
        callVehiclePanel.setMaximumSize(new java.awt.Dimension(2147483647, 33));
        callVehiclePanel.setLayout(new javax.swing.BoxLayout(callVehiclePanel, javax.swing.BoxLayout.X_AXIS));
        callVehiclePanel.add(filler3);

        callVehicleField.setAlignmentX(0.0F);
        callVehicleField.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        callVehiclePanel.add(callVehicleField);
        callVehiclePanel.add(filler1);

        callButton.setText("Anfunken");
        callVehiclePanel.add(callButton);
        callVehiclePanel.add(filler2);

        actionPanel.add(callVehiclePanel);

        responsePanel.setAlignmentX(0.0F);
        responsePanel.setLayout(new javax.swing.BoxLayout(responsePanel, javax.swing.BoxLayout.X_AXIS));
        responsePanel.add(filler4);

        repsoneEndMessageButton.setText("Verstanden, Ende");
        repsoneEndMessageButton.setEnabled(false);
        responsePanel.add(repsoneEndMessageButton);

        actionPanel.add(responsePanel);

        getContentPane().add(actionPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RadioUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton callButton;
    private javax.swing.JTextField callVehicleField;
    private javax.swing.JPanel callVehiclePanel;
    private javax.swing.JLabel demoLeftLabel;
    private javax.swing.JPanel demoLeftPanel;
    private javax.swing.JPanel demoRadioRequest;
    private javax.swing.Box.Filler demoRadioRequestFiller;
    private javax.swing.JLabel demoRadioRequestLabel;
    private javax.swing.JLabel demoRadioRequestVehicleLabel;
    private javax.swing.Box.Filler demoRightFiller;
    private javax.swing.JLabel demoRightLabel;
    private javax.swing.JPanel demoRightPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JScrollPane messagesScrollPanel;
    private javax.swing.JButton repsoneEndMessageButton;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JScrollPane requestScrollPanel;
    private javax.swing.JPanel responsePanel;
    // End of variables declaration//GEN-END:variables
}
